openapi: 3.0.1
info:
  title: Cloud Service API
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/v1/promo":
    post:
      tags:
        - promo-controller
      operationId: usePromo
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              "$ref": "#/components/schemas/UsePromoRequest"
      responses:
        '200':
          description: OK

  "/api/v1/workspaces":
    post:
      tags:
        - workspace-controller
      operationId: createWorkspace
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              "$ref": "#/components/schemas/CreateWorkspaceRequest"
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                "$ref": "#/components/schemas/WorkspaceResponse"
    get:
      tags:
        - workspace-controller
      operationId: getWorkspaces
      parameters:
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/PageWorkspaceResponse"
  "/api/v1/users":
    post:
      tags:
        - user-controller
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              "$ref": "#/components/schemas/CreateUserRequest"
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                "$ref": "#/components/schemas/CreateUserResponse"
        '400':
          $ref: "#/components/responses/BadRequest"
  "/api/v1/auth":
    post:
      tags:
        - user-controller
      operationId: authUser
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              "$ref": "#/components/schemas/AuthUserRequest"
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                "$ref": "#/components/schemas/TokenResponse"
        '400':
          $ref: "#/components/responses/BadRequest"
  "/api/v1/workspaces/{workspaceId}":
    post:
      tags:
        - user-controller
      operationId: addNewWorkspace
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
    delete:
      tags:
        - workspace-controller
      operationId: deleteWorkspace
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
    patch:
      tags:
        - workspace-controller
      operationId: changeWorkspaceName
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json;charset=utf-8:
            schema:
              "$ref": "#/components/schemas/ChangeWorkspaceNameRequest"
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                "$ref": "#/components/schemas/WorkspaceResponse"
  "/api/v1/files/workspaces/{workspaceId}":
    get:
      tags:
        - file-controller
      operationId: getFilesInfo
      parameters:
        - name: pageNumber
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                $ref: "#/components/schemas/PageFileResponse"
    post:
      tags:
        - file-controller
      operationId: uploadFiles
      parameters:
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data;charset=utf-8:
            schema:
              type: object
              required:
                - files
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Массив загружаемых файлов
      responses:
        '200':
          description: OK
  "/api/v1/workspaces/all":
    get:
      tags:
        - workspace-controller
      operationId: getAllWorkspaces
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WorkspaceResponse"
  "/api/v1/files/{fileId}/workspaces/{workspaceId}":
    get:
      tags:
        - file-controller
      operationId: getFile
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/octet-stream;charset=utf-8:
              schema:
                type: string
                format: binary
    delete:
      tags:
        - file-controller
      operationId: deleteFile
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: workspaceId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
components:
  schemas:
    UsePromoRequest:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          format: uuid
    Page:
      type: object
      properties:
        content:
          type: array
          items:
            anyOf: [ ]
        totalPages:
          type: integer
        totalElements:
          type: integer
    PageFileResponse:
      allOf:
        - $ref: "#/components/schemas/Page"
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: "#/components/schemas/FileResponse"
    PageWorkspaceResponse:
      allOf:
        - $ref: "#/components/schemas/Page"
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: "#/components/schemas/WorkspaceResponse"
    CreateWorkspaceRequest:
      required:
        - name
      type: object
      properties:
        name:
          type: string
    ChangeWorkspaceNameRequest:
      allOf:
        - $ref: "#/components/schemas/CreateWorkspaceRequest"
    WorkspaceResponse:
      type: object
      properties:
        workspaceId:
          type: string
          format: uuid
        name:
          type: string
        userId:
          type: string
          format: uuid
    CreateUserRequest:
      required:
        - username
        - password
        - workspaceName
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthUserRequest:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    TokenResponse:
      required:
        - token
      type: object
      properties:
        token:
          type: string
    CreateUserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        token:
          type: string
    FileResponse:
      type: object
      properties:
        fileId:
          type: string
          format: uuid
        fileName:
          type: string
    ErrorResponse:
      properties:
        message:
          type: string
        status:
          type: integer
        code:
          type: string
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'